# Generated by Django 4.2.5 on 2023-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoja',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
